### PR TITLE
Partial Reforged 0.9.0 data

### PR DESCRIPTION
**Pull request by ividyon**
Hi,

unfortunately I was not able to get the .fmg.json files from DSMS; it bugs out for me in the current version, I get `.fmg.fmg.json` files with only `{}` empty brackets in them. So this is only a partial data drop!

### CODE REVIEW

**Comment by ividyon** [comment]
Another important topic @ThomasJClark: In this version of Reforged we have moved to having some extra UI icons in the game, which are usually inserted into menu strings with quasi-HTML Scaleform tags. So I feel like code might be needed to strip tags and trim the strings before feeding them to the calculator...

**Comment by ThomasJClark** [comment]
thanks @ividyon, I'll merge to a development branch and take a look at the FMG issue. if we can't get the DSMS export to work, we can leave the FMGs alone and temporarily hardcode the new weapon names

**Comment by ividyon** [comment]
@ThomasJClark I recommend using WitchyBND or Yabber (Witchy is the successor) to unpack the item/menu.msgbnd.dcx file, and then to Also turn the FMG file into XML Format, and switching to using the XML instead. Depending on DSMS json format is a little awkward.

**Comment by ThomasJClark** [comment]
DSMapStudio's FMG -> JSON export actually worked for me (the site is updated now), but good to know that exists for the future

**Pull request merged**
