### PR TITLE
Add support for Elden Ring Reforged

### LINKED ISSUE #7: Consider adding values from some popular overhaul mods
In particular, [Elden Ring Reforged](https://www.nexusmods.com/eldenring/mods/541)

### PR DESCRIPTION
**Pull request by ThomasJClark**
https://www.nexusmods.com/eldenring/mods/541

https://err.fandom.com/wiki/ELDEN_RING_Reforged_Wiki

Additionally:

- Automatically hide status effect columns that don't apply to any weapons
  - ERR adds death blight weapons, but I don't want to add a column that's always empty in vanilla
- Show unarmed as a unique fist weapon
  - ERR enhances unarmed damage. Might as well also include it for vanilla
- Add a dropdown for selecting the game version
  - Current options are 1.09 and reforged
  - If patch 1.10 changes any weapon stats, I'll use this to allow selecting previous versions
- Various refactors, logging, and performance improvements

---

- [x] Investigate new scaling curves that sometimes result in NaN attack power
  - Resolved, two handing strength scaling bonus is disabled for ERR
- [x] Filter out affinities for somber weapons
- [x] Import icons for new affinities
  - Resolved, don't show affinity icons for ERR
- [x] Add Death Blight column  
  - Added icon.
  - Updated table to only include columns for status effects that apply to at least one selected weapon, so this column isn't shown in vanilla.
- [x] Verify that the calculations match in-game stats

Resolves #7

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
Consider adding the mod version in the drop down menu

**Comment by AndriySvyryd** [comment]
Also, filter out affinities for unique/somber weapons as those aren't available in the game

**Comment by AndriySvyryd** [comment]
In what cases do you get NaN AP? I wonder if the spreadsheet handles them correctly.

**Comment by ThomasJClark** [comment]
> In what cases do you get NaN AP? I wonder if the spreadsheet handles them correctly.

CalcCorrectGraph 1, which is used for strength scaling on heavy weapons. It only goes up to 99 in ERR, which is possible to exceed by two handing. My implementation of CalcCorrectGraph didn't handle attributes going past max value of the graph very well.

<table>
<tr><th></th><th>Vanilla</th><th>Reforged</th></tr>
<tr><td><code>ID</code></td><td>1</td><td>1</td></tr>
<tr><td><code>stageMaxVal0</code></td><td>1</td><td>0</td></tr>
<tr><td><code>stageMaxVal1</code></td><td>20</td><td>30</td></tr>
<tr><td><code>stageMaxVal2</code></td><td>60</td><td>50</td></tr>
<tr><td><code>stageMaxVal3</code></td><td>80</td><td>80</td></tr>
<tr><td><code>stageMaxVal4</code></td><td>150</td><td>99</td></tr>
<tr><td><code>stageMaxGrowVal0</code></td><td>0</td><td>0</td></tr>
<tr><td><code>stageMaxGrowVal1</code></td><td>35</td><td>40</td></tr>
<tr><td><code>stageMaxGrowVal2</code></td><td>75</td><td>60</td></tr>
<tr><td><code>stageMaxGrowVal3</code></td><td>90</td><td>85</td></tr>
<tr><td><code>stageMaxGrowVal4</code></td><td>110</td><td>100</td></tr>
<tr><td><code>adjPt_maxGrowVal0</code></td><td>1.2</td><td>1.041</td></tr>
<tr><td><code>adjPt_maxGrowVal1</code></td><td>-1.2</td><td>-0.862</td></tr>
<tr><td><code>adjPt_maxGrowVal2</code></td><td>1</td><td>0.834</td></tr>
<tr><td><code>adjPt_maxGrowVal3</code></td><td>1</td><td>-0.927</td></tr>
<tr><td><code>adjPt_maxGrowVal4</code></td><td>1</td><td>1</td></tr>
</table> 

I assume the correct behavior is to cap out strength scaling at 99, but maybe @ividyon can provide some insight if that's the intended change in the mod.

**Comment by AndriySvyryd** [comment]
> CalcCorrectGraph 1, which is used for strength scaling on heavy weapons. It only goes up to 99 in ERR, which is possible to exceed by two handing. My implementation of CalcCorrectGraph didn't handle attributes going past max value of the graph very well.

Indeed, the spreadsheet has the same issue.

> I assume the correct behavior is to cap out strength scaling at 99, but maybe @ividyon can provide some insight if that's the intended change in the mod.

Looks like that's how it works in-game. 2H still deals a bit more damage due to different correction in AtkParam

**Comment by ividyon** [comment]
@ThomasJClark In ERR there is no bonus to Str from two handing (for damage purposes; it's still there for meeting requirements) so it's indeed just regular scaling to 99. Indeed the damage boost to 2h comes from atkparam

There are also no new icons for affinities, instead they were edited out altogether.

**Comment by ividyon** [comment]
@AndriySvyryd 

`isDisableBotHahndsAtkBonus` in the according `AtkParam_Pc` entries

**Pull request merged**
